name: nemu-pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - openjdk=11              # Required for MACSE
  - nextflow
  - seqkit
  - taxonkit
  - blast                   # BLAST+
  - mafft
  - macse
  - goalign
  - iqtree=2.2.0
  - newick_utils            # nw_reroot, nw_distance, etc.
  - treeshrink
  - imagemagick
  - pip
  - pip:
    - pymutspec==0.0.14     # Installs collect_mutations.py, calculate_mutspec.py TODO check env creation again