name: nemu
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - openjdk=17
  - nextflow=25.10
  - seqkit
  - taxonkit
  - blast                   # BLAST+
  - mafft
  - macse
  - goalign
  - iqtree=2.2.0
  - newick_utils            # nw_reroot, nw_distance, etc.
  - treeshrink
  - librsvg
  # - cairosvg
  - gzip
  - jq
  - numpy<2.0
  - pandas<2.0
  - seaborn==0.12.2
  - biopython>=1.75
  - pip
  - pip:
    - pymutspec==0.0.14     # Installs collect_mutations.py, calculate_mutspec.py TODO check env creation again